apiVersion: v1
kind: ConfigMap
metadata:
  namespace: folder4study
  name: prometheus
  labels:
    app: prometheus
    version: latest
data:
  prometheus.yml: |-
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
    scrape_configs:
    - job_name: 'prometheus'
      static_configs:
        - targets: ['127.0.0.1:9090']
