apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: folder4study
  labels:
    app: prometheus
    version: latest
spec:
  type: LoadBalancer
  selector:
    app: prometheus
  ports:
    - name: port
      port: 9090
      targetPort: port
